<?php
require_once("Interfaces/IEntregarTarea.php");
require_once("Interfaces/IRevisarNota.php");

class Estudiante extends Persona implements IEntregarTarea, IRevisarNota
{
    private $codEstudiante;

    /**
     * @return mixed
     */
    public function getCodEstudiante()
    {
      return $this->codEstudiante;
    }

    /**
     * @param mixed $codEstudiante
     */
    public function setCodEstudiante($codEstudiante)
    {
      $this->codEstudiante = $codEstudiante;
    }

    function entregarTarea() {
      return 'Estudiante ' .$this->getNombre().'('.$this->getCodEstudiante().') entrega tarea'.PHP_EOL;
    }

    public function revisarNota()
    {
      return "Estudiante revisar nota de la tarea".PHP_EOL;
    }

    public function consultarDatos()
    {
      return PHP_EOL."Estudiante-> ".parent::consultarDatos(). "| Cod: ".$this->getCodEstudiante(); // TODO: Change the autogenerated stub
    }

}
