<?php

class PadreFamilia extends Persona
{
  private $padreId;

  /**
   * @return mixed
   */
  public function getPadreId()
  {
    return $this->padreId;
  }

  /**
   * @param mixed $padreId
   */
  public function setPadreId($padreId)
  {
    $this->padreId = $padreId;
  }

  /**
   * @return string
   */
  public function revisarNota()
  {
    return "Padre revisa nota de la tarea";
  }

  /**
   * @return string
   */
  public function consultarDatos()
  {
    return PHP_EOL."Padre de Familia-> ".parent::consultarDatos() ." | IdPadre:". $this->getPadreId(); // TODO: Change the autogenerated stub
  }

  /**
   * Sobre escribe el método cargarDatos de persona y agrega el atributo de identificación correpondiente al padre de familia
   * @param $nombre
   * @param $apellido
   * @param $fechaNacimiento
   * @param $correo
   * @param int $padreId
   */
  public function cargarDatos($nombre, $apellido, $fechaNacimiento, $correo, $padreId = 0)
  {
    parent::cargarDatos($nombre, $apellido, $fechaNacimiento, $correo); // TODO: Change the autogenerated stub
    $this->setPadreId($padreId);
  }
}
