<?php

class Profesor extends Persona
{
    private $profesorId;

    /**
     * @param mixed $profesorId
     */
    public function setProfesorId($profesorId)
    {
      $this->profesorId = $profesorId;
    }

    /**
     * @return mixed
     */
    public function getProfesorId()
    {
      return $this->profesorId;
    }

    public function asignarTarea($estudiante)
    {
      return 'Profesor(a) '.$this->getNombre().'('.$this->getProfesorId().') asigna tarea a '. $estudiante->getNombre()." ".PHP_EOL;
    }

    public function calificaTarea($estudiante)
    {
      return 'Profesor(a) '.$this->getNombre().'('.$this->getProfesorId().') califica la tarea del estudiante '.$estudiante->getNombre().PHP_EOL;
    }

    public function consultarDatos()
    {
      return PHP_EOL."Profesor(a)-> ".parent::consultarDatos()." | IdProfesor: ". $this->getProfesorId(); // TODO: Change the autogenerated stub
    }

    /**
     * Sobre escribe el método cargarDatos de persona y agrega el atributo correpondiente al profesor
     * @param $nombre
     * @param $apellido
     * @param $fechaNacimiento
     * @param $correo
     * @param int $profesorId
     */
    public function cargarDatos($nombre, $apellido, $fechaNacimiento, $correo, $profesorId = 0)
    {
      parent::cargarDatos($nombre, $apellido, $fechaNacimiento, $correo); // TODO: Change the autogenerated stub
      $this->setProfesorId($profesorId);
    }

}
