<?php

class Profesor extends Persona
{
    private $profesorId;

    /**
     * @param mixed $profesorId
     */
    public function setProfesorId($profesorId)
    {
      $this->profesorId = $profesorId;
    }

    /**
     * @return mixed
     */
    public function getProfesorId()
    {
      return $this->profesorId;
    }

    public function asignarTarea()
    {
      return 'Profesor(a) '.$this->getNombre().'('.$this->getProfesorId().') asigna tarea';
    }

    public function calificaTarea()
    {
      return 'Profesor(a) '.$this->getNombre().'('.$this->getProfesorId().') califica tarea';
    }

    /**
     * Permite ver los datos del profesor como string, cuando al llamarlo con echo
     * @return string
     */
    public function __toString()
    {
        return parent::__toString() ." ". $this->getProfesorId(); // TODO: Change the autogenerated stub
    }
}
